config/routes.rb
Rails.application.routes.draw do
  get '/email_setting', to: 'email_setting#index'
  post '/email_setting', to: 'email_setting#submit'

  root 'users#index'
  resources :users
  post '/users/:id/generate_token', to: 'users#generate_token', as: 'users_generate_token'
  post '/users/:id/destroy_token', to: 'users#destroy_token', as: 'users_destroy_token'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :user

  def self.generate(user)
    @token = Token.new
    @token.user_id = user.id
    @token.nonce = SecureRandom.uuid.gsub(/\-/,'')
    @token.save
    return @token
  end

  def self.consume(nonce)
    @token = Token.find_by_nonce(nonce)
    return nil if @token.nil?
    @user = User.find_by_id(@token.user_id)
    @token.destroy
    return @user
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :tokens

  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i

  before_save { self.email = email.downcase }

  validates :name, presence: true
  validates :email, presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: EMAIL_REGEX, multiline: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/email_setting_controller.rb
class EmailSettingController < ApplicationController

  def index
    email = params[:email]
    token = params[:token]
    if not email.nil? and not token.nil?
      user_by_email = User.find_by_email(email)
      token_by_nonce = Token.find_by_nonce(token)
      user_by_token = token_by_nonce.present? ? User.find(Token.find_by_nonce(token).user_id) : nil
      if user_by_email.present? and user_by_token.present? and user_by_email.eql? user_by_token
        @email = email
        @token = token
        @receive_marketing = user_by_email.receive_marketing
        @receive_articles = user_by_email.receive_articles
        @receive_digest = user_by_email.receive_digest
      end
    end
  end

  # POST /email_setting
  def submit
    email = params[:email]
    @user = User.find_by_email(email)
    token = params[:token]
    @user_by_token = Token.consume(token)

    return redirect_to '/email_setting', alert: "invalid email" if @user.nil?
    return redirect_to '/email_setting', alert: "invalid token" if @user_by_token.nil?
    return redirect_to '/email_setting', alert: "user/token mismatch" if not @user.eql? @user_by_token

    if @user.update(email_setting_params)
      token = Token.generate(@user)
      redirect_to '/email_setting', notice: "User was successfully updated.Use #{token.nonce} for next update"
    else
      redirect_to '/email_setting', alert: "error"
    end
  end

  private
    def email_setting_params
      params.permit(:email, :receive_marketing, :receive_articles, :receive_digest)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :generate_token]

  # GET /users
  # GET /users.json
  def index
    session[:return_to] = request.url
    @users = User.all.order(:id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    session[:return_to] = request.url
    @tokens = Token.where(user_id: @user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def generate_token
    @token = Token.generate(@user)
    respond_to do |format|
      format.html { redirect_to session.delete(:return_to), notice: 'Token was successfully created.' }
      format.json { head :no_content }
    end
  end

  def destroy_token
    @token = Token.find(params[:id])
    @user = User.find(@token.user_id)
    @token.destroy
    respond_to do |format|
      format.html { redirect_to session.delete(:return_to), notice: 'Token was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :receive_marketing, :receive_articles, :receive_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_setting_helper.rb
module EmailSettingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/email_setting/_form.html.erb
<div class="col-sm-offset-3 col-sm-6 panel panel-default">

<%= form_tag '/email_setting', method: 'post' do %>
  <div class="form-group">
    <label for="email">Email</label>
    <%= email_field_tag :email, @email, :placeholder =>'Enter your email address', :class => 'form-control' %>
  </div>
  <div class="form-group">
    <label for="nonce">Nonce</label>
    <%= text_field_tag :token, @token, :placeholder => "Enter an associated token", :class => 'form-control'  %>
  </div>
  <div class="form-group form-check">
    <%= hidden_field_tag :receive_marketing, false %>
    <%= check_box_tag :receive_marketing, nil, @receive_marketing %>
    Receive Marketing
  </div>
  <div class="form-group form-check">
    <%= hidden_field_tag :receive_articles, false %>
    <%= check_box_tag :receive_articles, nil, @receive_articles %>
    Receive Articles
  </div>
  <div class="form-group form-check">
    <%= hidden_field_tag :receive_digest, false %>
    <%= check_box_tag :receive_digest, nil, @receive_digest %>
    Receive Digest
  </div>
  <div>
    <input id="all" name="all" type="checkbox" />
    Toggle All
  </div>
  <br>
  <div class="actions">
    <%= submit_tag "Update", class: "btn btn-large btn-primary"%>
  </div>
  <br>
<% end %>
</div>

app/views/email_setting/index.html.erb
<h4>Edit User Email Settings</h4>
<br>
<%= render 'form' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "The Information Code Challenge", root_path, class: 'navbar-brand' %>
      <ul class="nav nav-inline">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Users', users_path %></li>
<li><%= link_to 'Email Settings', email_setting_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "The Information Code Challenge" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Code Challenge" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field form-group form-check">
    <%= f.label :receive_marketing, class: 'checkbox' do %>
      <%= f.check_box :receive_marketing %>
      Receive Marketing
    <% end %>
  </div>

  <div class="field form-group form-check">
    <%= f.label :receive_articles, class: 'checkbox' do %>
      <%= f.check_box :receive_articles %>
      Receive Articles
    <% end %>
  </div>

  <div class="field form-group form-check">
    <%= f.label :receive_digest, class: 'checkbox' do %>
      <%= f.check_box :receive_digest %>
      Receive Digest
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Receive marketing</th>
      <th>Receive articles</th>
      <th>Receive digest</th>
      <th>First Nonce</th>
      <th colspan="4" class="center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td class='center'><%= user.receive_marketing %></td>
        <td class='center'><%= user.receive_articles %></td>
        <td class='center'><%= user.receive_digest %></td>
        <td><% user.tokens.each do |token| %>
              <%= token.nonce %>
            <% end %>
        </td>
        <td><%= link_to 'Generate New Token', users_generate_token_path(user), method: :post %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Receive marketing:</strong>
  <%= @user.receive_marketing %>
</p>

<p>
  <strong>Receive articles:</strong>
  <%= @user.receive_articles %>
</p>

<p>
  <strong>Receive digest:</strong>
  <%= @user.receive_digest %>
</p>

<h6>Tokens</h6>
<table class="table">
  <thead>
    <tr>
      <th>Nonce</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.nonce %></td>
        <td><%= link_to 'Destroy', users_destroy_token_path(token.id), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Generate New Token', users_generate_token_path(@user), method: :post %> |
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>